library(tidyverse)
library(igraph)

partes_tesis <- tibble::tribble(
                    ~codigo, ~x, ~y,                                                                                                                                                                                                                                                                                                                           ~nodo_desc,          ~tarea,             ~origen,                                                                                 ~detalle,
                       "h1",  1,  5,                                                                                                                                                                      "La red agregada total (desde 1996 a 2016) es de mundo pequeño puesto que es una característica presente en la mayoría de las redes de coautorías científicas.",     "hipotesis",        "Plan tesis",                                                          "mundo pequenio y libre escala",
                       "h2",  1, 10,                                                                                                                                                                  "La cantidad de autores aumenta en el tiempo debido al crecimiento de la disciplina en el país, lo que se refleja en un aumento en la cantidad de nodos en la red.",     "hipotesis",        "Plan tesis",                                                  "cuidado con crecimiento de disciplina",
                       "h3",  1, 15,                                                                                                                                                                                  "Los autores fundadores se refuerzan en el tiempo, lo cual se verá reflejado en mayores medidas de grado, intermediación y fuerza de colaboración.",     "hipotesis",        "Plan tesis",                                                "verificar en diferentes T las metricas.",
                       "h4",  1, 20,                                                                                                                                                                  "Los componentes más grandes absorben a los más pequeños a lo largo del tiempo, dado que autores periféricos pasan a trabajar en conjunto con autores principales.",     "hipotesis",        "Plan tesis",                        "si se abosrben componentes en tiempo, los links que se generan.",
                       "t1",  3,  1,                                     "Desambiguación de nombres de autor, se considera un proceso necesario para el armado de la base de datos. Esto puede verse reflejado en el trabajo de Morel et al. (2009) [ 9 ] y una fundamentación más extensa de por qué realizar esta tarea se observa en el trabajo de Tang (2010) [ 10 ]",         "tarea",             "kumar",                                                                                     "--",
                       "t2",  3,  3,                                                                                                                                                                                    "Visualización de la red. Se plantea tener diferentes puntos de vista que pueden ayudar con el análisis de la red complementario a las métricas.",         "tarea",             "kumar",                                                                                     "--",
                       "t3",  3,  5,                                                                                                         "Análisis de mundo pequeño y red de libre escala (Small World & scale free) para la red agregada total y para cada instante temporal, para poder comparar la red obtenida con simulaciones basadas en sus particularidades.",              NA,             "kumar",                                                                                     "--",
                       "t4",  3,  7,                                                                                                                                                                                 "El tamaño del componente gigante y su evolución en el tiempo. Este análisis brinda la posibilidad de ver qué tan cohesiva o fragmentada es la red.",         "tarea",             "kumar",                                                                                     "--",
                       "t5",  3,  9,                                                                                                                           "El componente gigante podría significar la principal actividad de investigación; mientras que los otros componentes pueden ser agrupamientos especializados o sub-comunidades. (Fatt et al., 2010) [ 8 ]",         "tarea",             "kumar",                                                                                     "--",
                       "t6",  3, 11,                                                                                                   "Búsqueda de Comunidades.  Este análisis permite evaluar la ubicación e interacciones entre los distintos grupos de investigación dentro de la red y buscarles un sentido a las comunidades dentro del contexto de la disciplina.",         "tarea",           "koseglu",                                                                                     "--",
                       "t7",  3, 13,   "Métricas generales a fin de analizar por períodos de agregación y la red completa. De las métricas que se tendrán en cuenta se destacan: (a) artículos con más de un autor, (b) autores que participan en artículos con más de un autor, (c) índice de colaboración, siendo este último una relación entre las medidas (b) / (c)",         "tarea",           "koseglu",                                                                                     "--",
                       "t8",  3, 15,                "Patrones de autoría, es decir, cuántos artículos por cantidad de autores existen en los diferentes periodos, dejando expuesto cuantos participan individualmente, en colaboración de a 2 autores, o más. Este análisis es útil para evaluar si existen tendencias de mayor trabajo en equipo a lo largo del tiempo.",         "tarea",           "koseglu",                                                                                     "--",
                       "t9",  3, 17, "Comparación con otras redes de coautoría realizadas en otros trabajos utilizando métricas que están presentes en todos ellos por ejemplo: (a) artículos por autor, (b) coeficiente de clustering (transitividad), (c) tamaño del componente principal, (d) componente principal representado en porcentaje, y (e) distancia media.",         "tarea",           "koseglu",                                                                                     "--",
                       "s1",  5,  1,                                                                                                                                                                                                                                                                                                           "Capitulo 1: introduccion", "seccion tesis", "Escritura – tesis",    "Establecer contexto, plantear problema, plantear plan de solucion, pie a capitulo 2",
                       "s2",  5,  3,                                                                                                                                                                                                                                                                                                       "Capitulo 2: generacion Datos", "seccion tesis", "Escritura – tesis",     "intro de capitulo, materiales y metodos, resultados de procesos, resumen, pie al 3",
                       "s3",  5,  5,                                                                                                                                                                                                                                                                                                 "Capitulo 3: generacion herramienta", "seccion tesis", "Escritura – tesis",               "intro del capitulo, materiales y metodos, resumen del capitulo, pie al 4",
                       "s4",  5,  7,                                                                                                                                                                                                                                                                                           "Capitulo 4: analisis de red de coautoria", "seccion tesis", "Escritura – tesis", "intro del capitulo contestar hipotesis. Contestar objetivos. Resumen capitulo pie al 5",
                       "s5",  5,  9,                                                                                                                                                                                                                                                                                                     "Capitulo 5: discucion & cierre", "seccion tesis", "Escritura – tesis",                          "Intro, discucion, cierre, trabajos futuros.  Agradecimientos.",
                       "s6",  5, 11,                                                                                                                                                                                                                                                                                             "ANEXO: software y librerías utilizadas", "seccion tesis", "Escritura – tesis",                                                                   "creditos al software",
                       "s7",  5, 13,                                                                                                                                                                                                                                                                                             "ANEXO: Detalle estandarización autores", "seccion tesis", "Escritura – tesis",                               "detalle de como se realizo la estandarizacion de autores",
                       "s8",  5, 15,                                                                                                                                                                                                                                                                                                 "ANEXO: Detalle consideraciones PDF", "seccion tesis", "Escritura – tesis",                                                                   "detalle de los pdf\\",
                       "s9",  5, 17,                                                                                                                                                                                                                                                                                                "ANEXO: Detalle procesamiento bibTEX", "seccion tesis", "Escritura – tesis",                                                                  "detalle de los bibtex",
                      "s10",  5, 19,                                                                                                                                                                                                                                                                          "ANEXO: Detalle de algoritmos para búsqueda de comunidades", "seccion tesis", "Escritura – tesis",                                  "detalle de algoritmos para la busqueda de comunidades",
                       "a1",  7,  1,                                                                                                                                                                                                                                                                                                          "cosideraciones: generales",   "seccion app",    "desarrollo app",                                                                        "consideraciones",
                       "a2",  7,  3,                                                                                                                                                                                                                                                                                                               "consideraciones: EDA",   "seccion app",    "desarrollo app",                                                                  "analisis exploratorio",
                       "a3",  7,  5,                                                                                                                                                                                                                                                                                                   "analisis estatico: visualizacion",   "seccion app",    "desarrollo app",                                                                          "visualizacion",
                       "a4",  7,  7,                                                                                                                                                                                                                                                                                             "analisis estatico: articulos asociados",   "seccion app",    "desarrollo app",                                                                           "datos crudos",
                       "a5",  7,  9,                                                                                                                                                                                                                                                                                                  "analisis estatico: estructura red",   "seccion app",    "desarrollo app",                                                                       "estructura grafo",
                       "a6",  7, 11,                                                                                                                                                                                                                                                                                             "analisis estatico: comparacion modelos",   "seccion app",    "desarrollo app",                                                                                "modelos",
                       "a7",  7, 13,                                                                                                                                                                                                                                                                                                     "analisis estatico: comunidades",   "seccion app",    "desarrollo app",                                                                            "comunidades",
                       "a8",  7, 15,                                                                                                                                                                                                                                                                                          "analisis temporal: visualizacion dinamica",   "seccion app",    "desarrollo app",                                                                     "temporal evolucion",
                       "a9",  7, 17,                                                                                                                                                                                                                                                                                           "analisis temporal: metricas red por anio",   "seccion app",    "desarrollo app",                                                                       "metricas anuales",
                      "a10",  7, 19,                                                                                                                                                                                                                                                                                         "analisis temporal: metricas red acumuladas",   "seccion app",    "desarrollo app",                                                                    "metricas acumuladas",
                      "a11",  7, 21,                                                                                                                                                                                                                                                                                     "analisis temporal: metricas nodos top N tiempo",   "seccion app",    "desarrollo app",                                                                         "metricas top n",
                      "a12",  7, 23,                                                                                                                                                                                                                                                                          "analisis temporal: metricas nodos top N tiempo acumuladas",   "seccion app",    "desarrollo app",                                                                 "metricas top n totales"
                    )


grafo_vacio <- make_empty_graph(n = 0, directed = FALSE) 

hipotesis <- partes_tesis %>% filter(str_detect(codigo,pattern = 'h')) %>% pull(codigo)
tareas <- partes_tesis %>% filter(str_detect(codigo,pattern = 't')) %>% pull(codigo)
secciones <- partes_tesis %>% filter(str_detect(codigo,pattern = 's')) %>% pull(codigo)

grafo_resultado <- grafo_vacio +
    igraph::vertices(hipotesis,color='red') +
    igraph::vertices(tareas,color='blue') +
    igraph::vertices(secciones,color='green')

degree(grafo_resultado)

visNetwork::visIgraph(grafo_resultado)
