if(!require(Rcpp)) {install.packages("Rcpp"); require(Rcpp);}
if(!require(devtools)) {install.packages("devtools"); require(devtools);}
if(!require(htmlwidgets)) {install.packages("htmlwidgets"); require(htmlwidgets);}
if(!require(jsonlite)) {install.packages("jsonlite"); require(jsonlite);}
# if(!require(jas1/RBioFabric)) {install.packages("jas1/RBioFabric"); require(jas1/RBioFabric);}
if(!require(tidyr)) {install.packages("tidyr"); require(tidyr);}
if(!require(dplyr)) {install.packages("dplyr"); require(dplyr);}
if(!require(purrr)) {install.packages("purrr"); require(purrr);}
if(!require(stringr)) {install.packages("stringr"); require(stringr);}
if(!require(stringi)) {install.packages("stringi"); require(stringi);}
if(!require(lubridate)) {install.packages("lubridate"); require(lubridate);}
if(!require(RSQLite)) {install.packages("RSQLite"); require(RSQLite);}
if(!require(DBI)) {install.packages("DBI"); require(DBI);}
if(!require(igraph)) {install.packages("igraph"); require(igraph);}
if(!require(ggplot2)) {install.packages("ggplot2"); require(ggplot2);}
if(!require(ggraph)) {install.packages("ggraph"); require(ggraph);}
if(!require(qgraph)) {install.packages("qgraph"); require(qgraph);}
if(!require(RColorBrewer)) {install.packages("RColorBrewer"); require(RColorBrewer);}
if(!require(visNetwork)) {install.packages("visNetwork"); require(visNetwork);}
if(!require(shiny)) {install.packages("shiny"); require(shiny);}
if(!require(DT)) {install.packages("DT"); require(DT);}
if(!require(shinyWidgets)) {install.packages("shinyWidgets"); require(shinyWidgets);}
if(!require(bsplus)) {install.packages("bsplus"); require(bsplus);}
if(!require(plotly)) {install.packages("plotly"); require(plotly);}
if(!require(shinydashboard)) {install.packages("shinydashboard"); require(shinydashboard);}
if(!require(ndtv)) {install.packages("ndtv"); require(ndtv);}
if(!require(intergraph)) {install.packages("intergraph"); require(intergraph);}
if(!require(assertive)) {install.packages("assertive"); require(assertive);}
if(!require(testthat)) {install.packages("testthat"); require(testthat);}
if(!require(igraphdata)) {install.packages("igraphdata"); require(igraphdata);}
if(!require(forcats)) {install.packages("forcats"); require(forcats);}
if(!require(visdat)) {install.packages("visdat"); require(visdat);}
if(!require(ggridges)) {install.packages("ggridges"); require(ggridges);}
if(!require(skimr)) {install.packages("skimr"); require(skimr);}
if(!require(ggrepel)) {install.packages("ggrepel"); require(ggrepel);}
if(!require(survival)) {install.packages("survival"); require(survival);}
if(!require(cluster)) {install.packages("cluster"); require(cluster);}
if(!require(rpart)) {install.packages("rpart"); require(rpart);}
if(!require(Hmisc)) {install.packages("Hmisc"); require(Hmisc);}
